### ISSUE TITLE
Package dependency refers to rviz version 1 not 2

### ISSUE THREAD

**Issue by robin-mueller** [CommonplaceRobotics/iRC_ROS#106]
**Description**
The dependency for rviz in the [desciption package](https://github.com/CommonplaceRobotics/iRC_ROS/blob/3d485ad15ef8cf4ef4298322e1dae8ceaeca15a9/irc_ros_description/package.xml#L13) and the [hardware package](https://github.com/CommonplaceRobotics/iRC_ROS/blob/3d485ad15ef8cf4ef4298322e1dae8ceaeca15a9/irc_ros_hardware/package.xml#L23) refers to `rviz` whereas it should be `rviz2`.

**Your environment**

    ROS Distro: Humble
    OS Version: Ubuntu 22.04
    Branch/Commit hash: humble #3d485ad
    
**To Reproduce**
Running `rosdep check --from-paths src/iRC_ROS/`.

**Result**
```
...
ERROR[irc_ros_description]: Cannot locate rosdep definition for [rviz]
        rosdep key : rviz
        OS name    : ubuntu
        OS version : jammy
        Data:
<no data>

...
ERROR[irc_ros_hardware]: Cannot locate rosdep definition for [rviz]
        rosdep key : rviz
        OS name    : ubuntu
        OS version : jammy
        Data:
<no data>
...
```

If `rviz` is substituted with `rviz2` in the package.xml linked above the error won't occur.

**Comment by cpr-fer** [comment]
Hi @robin-mueller 

Thank you for your two issues! I just created a PR that should fix the issue, I'll merge it after testing it on my machine as well
