### ISSUE TITLE
Missing dependency reference for irc_ros_moveit_config in examples

### ISSUE THREAD

**Issue by robin-mueller** [CommonplaceRobotics/iRC_ROS#107]
**Description**
Package description for `irc_ros_examples` lacks dependency reference to `irc_ros_moveit_config`.

**Your environment**

    ROS Distro: Humble
    OS Version: Ubuntu 22.04
    Branch/Commit hash: humble #3d485ad
    
**To Reproduce**
Build with ` colcon build --packages-up-to irc_ros_examples` and run `ros2 launch irc_ros_examples pick_and_place.launch.py`.

**Result**
```
[ERROR] [launch]: Caught exception in launch (see debug for traceback): "package 'irc_ros_moveit_config' not found
```

Adding `<depend>irc_ros_moveit_config</depend>` [here](https://github.com/CommonplaceRobotics/iRC_ROS/blob/3d485ad15ef8cf4ef4298322e1dae8ceaeca15a9/irc_ros_examples/package.xml#L20) resolves this issue.

**Comment by cpr-fer** [comment]
Also fixed by #108, thank you again!
