### ISSUE TITLE
Failed to activate controller

### ISSUE THREAD

**Issue by Flauriane** [CommonplaceRobotics/iRC_ROS#112]
**Description**
I loaded the iRC_ROS repository and followed everything in the readme. but when lauch the pick and Place example and also other example using **LC_NUMERIC=en_US.UTF-8 ros2 launch irc_ros_moveit_config rebel.launch.py gripper:="ext_dio_gripper"** I get an some errors stating **Failled to active controller**. Still  now I wasn't able to slove it. Could someone help?
hier under are pictures with errors

![MicrosoftTeams-image](https://github.com/CommonplaceRobotics/iRC_ROS/assets/125724048/57b1e76a-a883-4901-b6c6-7703832a8135)

![MicrosoftTeams-image (3)](https://github.com/CommonplaceRobotics/iRC_ROS/assets/125724048/d3b4b391-f98a-4b71-9b9a-eebcc5b3de9c)
![MicrosoftTeams-image (2)](https://github.com/CommonplaceRobotics/iRC_ROS/assets/125724048/8105d399-b5e4-4ac0-8c07-02612397c8af)
![MicrosoftTeams-image (1)](https://github.com/CommonplaceRobotics/iRC_ROS/assets/125724048/fac32da7-87af-4d61-a949-cb5f3ab87aab)

**Comment by cpr-marcoh** [comment]
Sorry for the late reply! If you still have issues with this repository, please contact our support: support@cpr-robots.com
Are you connected to the CAN-bus of the robot? Or are you trying to connect to the robot via ethernet? In that case you have to set the _hardware_protocol_ to "cri"
`ros2 launch irc_ros_moveit_config rebel.launch.py gripper:="ext_dio_gripper" hardware_protocol="cri"`
