### ISSUE TITLE
parsing error on launch

### ISSUE THREAD

**Issue by JHeuverRiwo** [CommonplaceRobotics/iRC_ROS#80]
Since the commit on 21-04-23 I cannot launch any of the launchfiles. This issue is not present on the commit dated 19-4.

Taken steps:
- pull most recent changes on humble branch (from 21-4-23)
- remove all existing build and install files
- (on my workspace): $ colcon install --symlink-install 
- $ . install/setup.sh
- $ ros2 launch irc_ros_bringup rebel.launch.py

expected result:
depending on the arguments of the bringup launchfile, i'd have expected to see the launch file running the described actions such as launching rviz, making communication with the robot, starting up controllers etc.

actual result:
the following error message is printed to my terminal:
[ERROR] [launch]: Caught exception in launch (see debug for traceback): Unable to parse the value of parameter robot_description as yaml. If the parameter is meant to be a string, try wrapping it in launch_ros.parameter_descriptions.ParameterValue(value, value_type=str)

The only thing prior to the message is a message about the logging level, so there's hardly anything happening before I run into this error.

some remarks:
I tried some variations as arguments to the launch file, as well as some of the other launchfiles, including the one in the moveit_config package. All resulted in this error.

I do have nav2 and nav2 bringup installed and up to date. I am running ros2-humble on Ubuntu 22.04
thanks!

**Comment by cpr-fer** [comment]
I am looking into it, thanks again for finding and reporting so many issues! I am not sure yet about what may have caused the issue to appear with the 21-04 commit, as the rebel launch file has not changed with it.

Also I could only reproduce this with a clean build, so this tells me I should do this every time when testing before a PR.

**Comment by cpr-fer** [comment]
I think the issue is likely the added lines to the robot description files containing the "Issue #..." strings. It appears that '#' is not allowed without escaping them via quotes
